export const homeResume = {
  lastOperations: [
    {
      id: 10,
      concept: "Pizza",
      amount: "24.99",
      date: "2021-10-21",
      type: "expense",
      category: "food",
    },
    {
      id: 9,
      concept: "New game",
      amount: "65",
      date: "2021-10-18",
      type: "expense",
      category: "other",
    },
    {
      id: 8,
      concept: "Electricity  bill",
      amount: "500",
      date: "2021-10-08",
      type: "expense",
      category: "bills",
    },
    {
      id: 7,
      concept: "phone bill",
      amount: "33",
      date: "2021-10-08",
      type: "expense",
      category: "bills",
    },
    {
      id: 6,
      concept: "grandma gift",
      amount: "200",
      date: "2021-10-07",
      type: "income",
      category: "",
    },
    {
      id: 5,
      concept: "lunch",
      amount: "20",
      date: "2021-10-05",
      type: "expense",
      category: "food",
    },
    {
      id: 4,
      concept: "I loaded gasoline",
      amount: "150",
      date: "2021-10-04",
      type: "expense",
      category: "gas",
    },
    {
      id: 3,
      concept: "paycheck",
      amount: "2500",
      date: "2021-10-01",
      type: "income",
      category: "salary",
    },
    {
      id: 2,
      concept: "New suit",
      amount: "300",
      date: "2021-10-01",
      type: "expense",
      category: "clothes",
    },
    {
      id: 1,
      concept: "October rent",
      amount: "600",
      date: "2021-10-01",
      type: "expense",
      category: "rent",
    },
  ],
};
